### ISSUE TITLE
大佬可以加一个歌单歌词下载吗？

### ISSUE THREAD

**Issue by kengwang** [wwh1004/NLyric#2]
大佬可以考虑下歌单歌词下载吗。
既然已经登录了，也就可以获取歌单了
获取歌单歌词就不用再通过搜索获取ID了，但是文件名的话可以通过模糊匹配或者根据163的命名法来写
仅是建议，大佬如果不方便的话就忽略吧

**Comment by wwh1004** [comment]
感谢意见。issue先留着，以后有时间我再更新。最近确实挺忙的。估计国庆节可以更新。如果可以的话国庆提醒下我，可能我会忘掉。

**Comment by wwh1004** [comment]
如果只是按歌单来下载歌词，下载的歌词保存到哪里？然后下载的歌词是干什么用？没音频文件就一个歌词文件，我感觉没太大用处
