### ISSUE TITLE
[bug]搜索特定专辑时报错

### ISSUE THREAD

**Issue by pdtshtsg** [wwh1004/NLyric#4]
当读取到某些专辑下任意一首歌曲时报错，重试时每次都会出现。
附上错误截图，歌曲元数据与歌曲文件。

![报错截图](https://user-images.githubusercontent.com/58281930/69777118-ca6df280-11d9-11ea-8f46-578ffe3d3f17.png)

[4个专辑的元数据.txt](https://github.com/wwh1004/NLyric/files/3899817/4.txt)

歌曲文件链接 [http://www.wtmsb.cf/share/CdCCrBrK](http://www.wtmsb.cf/share/CdCCrBrK)

**Comment by wwh1004** [comment]
这个是引用的类库的bug，我看看能不能解决。

**Comment by wwh1004** [comment]
不对啊，你这文件有问题，我的播放器都打不开你的flac，MPC-BE直接卡死，元数据中的图片是坏的

**Comment by pdtshtsg** [comment]
但是在我这边 无论是foobar还是potplayer都能正常播放
![QQ截图20191129231125](https://user-images.githubusercontent.com/58281930/69877770-10bc7200-12fe-11ea-96fc-a4683e09fae9.png)
![QQ截图20191129231034](https://user-images.githubusercontent.com/58281930/69877783-17e38000-12fe-11ea-82e7-6ca3691233fd.png)

**Comment by wwh1004** [comment]
可能有些播放器不遵守格式。

flac格式：https://xiph.org/flac/format.html 页面搜索"The blocksize must be <=16384" 意思是每个块大小必须小于等于16MB，一个图片必须储存在一个块里面。还有其它文章，比如 https://community.mp3tag.de/t/cannot-embed-large-size-cover-image-s-for-flac/42923

你那个图片太大了，24mb，不符合格式的。50mb的flac，一半拿来装图片了。

mpc-be确实打不开那个flac
![Snipaste_2019-11-30_17-48-37](https://user-images.githubusercontent.com/27536652/69899209-12d60d80-139e-11ea-812d-d9282a4c12e3.png)

**Comment by pdtshtsg** [comment]
这样啊 明白了
