### ISSUE TITLE
[建议] 能不能在匹配失败是让用户输入歌曲的云音乐ID而不是专辑!

### ISSUE THREAD

**Issue by kengwang** [wwh1004/NLyric#5]
[建议] 能不能在匹配失败是让用户输入歌曲的云音乐ID而不是专辑!
![image](https://user-images.githubusercontent.com/30862240/69900902-3a37d500-13b4-11ea-91bd-cb53fac4eb4b.png)

**Comment by wwh1004** [comment]
你直接按回车不就可以了么，专辑匹配失败就是输入歌曲id

**Comment by wwh1004** [comment]
如果没错应该只会提示一次输入专辑，我记得我缓存了结果

**Comment by kengwang** [comment]
谢谢提醒,现在的路线是:
专辑匹配->专辑ID->带艺术家搜索->忽略艺术家搜索->网易云音乐ID

**Comment by kengwang** [comment]
可以提醒一下新手,因为我之前没看到输入的是**专辑**ID而输入了音乐ID导致匹配失败

**Comment by wwh1004** [comment]
上面写了是专辑ID，仔细读一下可以注意到
