### ISSUE TITLE
[BUG] 目前已知的歌曲歌词错误

### ISSUE THREAD

**Issue by kengwang** [wwh1004/NLyric#6]
1.
[Salt Is My Sugar (TheFatRat Remix)](http://music.163.com/song?id=555974256)
最后两句只获取到了翻译歌词并且掉了两句
>[02:59.14]宝贝如果你在听你一定懂得
>[03:08.29]你最好倾听这些然后点燃我内心的光芒
原曲歌词截图:
![image](https://user-images.githubusercontent.com/30862240/70367571-32a88c80-18dc-11ea-8803-af6b0e6868f5.png)

2.[HandClap](http://music.163.com/song?id=407839677)
时间严重出错
>[17:36.00]Too many troubles, all these lovers got you losing control 「这些暧昧情人麻烦不断 让你失去了理智」
>[37:02.00]Somebody save your soul cause you've been sinning in this city I know 「我知道你曾在这座城市无恶不作 直到有人将你灵魂救赎」
>[26:31.00]That I can make your hands clap 「我能让你情不自禁雀跃鼓掌」

原曲歌词截图
![image](https://user-images.githubusercontent.com/30862240/70367628-a2b71280-18dc-11ea-8583-2df04cd79595.png)

**Comment by kengwang** [comment]
获取的时候没任何报错

**Comment by wwh1004** [comment]
第一个，歌词格式是错误的
![image](https://user-images.githubusercontent.com/27536652/70374564-e0dd2200-192e-11ea-8727-e3426285d84f.png)
不太想为了兼容错误格式修改

**Comment by wwh1004** [comment]
第二个格式也是错的...

https://en.wikipedia.org/wiki/LRC_(file_format)

![image](https://user-images.githubusercontent.com/27536652/70374621-6791ff00-192f-11ea-8fef-ebff0cd15177.png)

不应该是:，应该是.

**Comment by kengwang** [comment]
毕竟还是少数,为了兼容不改代码,改一次就有很多连带错误
