### ISSUE TITLE
按照程序提示完成接下来的步骤？

### ISSUE THREAD

**Issue by AlucardNosferatu** [wwh1004/NLyric#7]
![image](https://user-images.githubusercontent.com/10172485/86509901-088d5d80-be1e-11ea-8cba-6a0e8149c11a.png)
然后。。。？怎么输入关键词？

**Comment by kengwang** [comment]
我已发现此BUG 已在Fork中修复
https://github.com/kengwang/NLyric-plus-plus/commit/6ef79e5944078738c1a3f72c6460ee85f0b015de
你可以模仿 第72行 添加
await TryDownloadLyricAsync(audioInfo);
希望原作者可以抽空修复下

**Comment by AlucardNosferatu** [comment]
> 我已发现此BUG 已在Fork中修复
> [kengwang@6ef79e5](https://github.com/kengwang/NLyric-plus-plus/commit/6ef79e5944078738c1a3f72c6460ee85f0b015de)
> 你可以模仿 第72行 添加
> await TryDownloadLyricAsync(audioInfo);
> 希望原作者可以抽空修复下

我先看下，大佬release的最新好像是在这个之前，我试了不能用，待会自己clone编一下再看看，多谢

**Comment by kengwang** [comment]
> > 我已发现此BUG 已在Fork中修复
> > [kengwang@6ef79e5](https://github.com/kengwang/NLyric-plus-plus/commit/6ef79e5944078738c1a3f72c6460ee85f0b015de)
> > 你可以模仿 第72行 添加
> > await TryDownloadLyricAsync(audioInfo);
> > 希望原作者可以抽空修复下
> 
> 我先看下，大佬release的最新好像是在这个之前，我试了不能用，待会自己clone编一下再看看，多谢

啊对，release忘更新了，因为那个fork我改了很多东西。本来打算自己用着方便的。

**Comment by AlucardNosferatu** [comment]
> > > 我已发现此BUG 已在Fork中修复
> > > [kengwang@6ef79e5](https://github.com/kengwang/NLyric-plus-plus/commit/6ef79e5944078738c1a3f72c6460ee85f0b015de)
> > > 你可以模仿 第72行 添加
> > > await TryDownloadLyricAsync(audioInfo);
> > > 希望原作者可以抽空修复下
> > 
> > 
> > 我先看下，大佬release的最新好像是在这个之前，我试了不能用，待会自己clone编一下再看看，多谢
> 
> 啊对，release忘更新了，因为那个fork我改了很多东西。本来打算自己用着方便的。在本地编译后就忘了上传release，只是Commit了一下

似乎不行，输入密码登录完就没下文了，直接按任意键继续，搜索信息是在哪里填写的？json里面么

![image](https://user-images.githubusercontent.com/10172485/86510139-bbaa8680-be1f-11ea-83e2-1adee1931969.png)

**Comment by kengwang** [comment]
……这个我就没法了 我试试我这边编译一遍

**Comment by wwh1004** [comment]
不在电脑上 但是我看了下 我代码没写错啊
我先获取的trackinfo
获取完全之后再下载的

**Comment by wwh1004** [comment]
你的歌是不是加密格式的 比如ncm什么的

**Comment by AlucardNosferatu** [comment]
> 你的歌是不是加密格式的 比如ncm什么的

这个歌是啥格式是啥意思，不是文件在网易服务器上么，额

**Comment by AlucardNosferatu** [comment]
> 你的歌是不是加密格式的 比如ncm什么的

还有就是我没太明白，关键词是怎么输入的，希望告知一下，感谢！

**Comment by wwh1004** [comment]
这个软件是下载歌词的 要求文件夹内有音频文件 然后软件会匹配网易云音乐的歌词 如果你本地没音频文件 一个歌词也不会下载的 所以我之前还没看懂你问了什么...
